### ISSUE TITLE
自动狗粮AB线提示ReferenceError？

### ISSUE THREAD

**Issue by AnLazyOtter** [babalae/bettergi-scripts-list#88]
@Kupder 大佬你好，我从仓库订阅了你制作的「自动狗粮 [AB线]」这个JS脚本，但是在运行时，被提示

> ReferenceError: settings is not defined

![Image](https://github.com/user-attachments/assets/4fd1c8d4-7f31-44e9-b2c2-f33f4e4010b2)

尝试自己排查了一下，但是感觉settings的解析应该是程序内置的才对，没能自己解决。故提个 issue 来请教下大佬该如何解决这个问题。
拜谢

**Comment by Kupder** [comment]
当前版本的bgi提示这个错误都需要添加到配置组内并设置自定义配置后使用，如下图所示：
![Image](https://github.com/user-attachments/assets/afb5b394-f05b-4c73-a63c-cd1a0a74f61f)

![Image](https://github.com/user-attachments/assets/df62c9ba-df4b-4602-9bf1-23cc379a4461)

**Comment by Yang-z** [comment]
可以下载目录 `bak/狗粮调度器@Yang-z`下的两个调度器文件，放入相应目录。同时订阅地图追踪-圣遗物目录下的A、B路线。
我平时都是用调度器去调试的。你可以尝试一下。所有路线都在持续尽最大可能去调优。
地图缩放稍微放大一点，75%左右差不多，不然绝云间锚点会点到旁边的副本。
目前残血会自动飞走加血，会影响部分路线重新开始。这个要等待bettergi版本更新。

**Comment by Yang-z** [comment]
@Kupder 对于地图追踪脚本的引用，能否引用原路径下的文件，你建立副本的话，我更新不到你那里。很多路线其实都已经优化过。

**Comment by Kupder** [comment]
> [@Kupder](https://github.com/Kupder) 对于地图追踪脚本的引用，能否引用原路径下的文件，你建立副本的话，我更新不到你那里。很多路线其实都已经优化过。

由于只能引用js脚本自身目录下的文件，因此无法直接引用Autopathing下的地图追踪脚本；如有需求的话后续会对您更新的地图追踪脚本进行可用性测试，并同步更新到js脚本中。
![Image](https://github.com/user-attachments/assets/b6d99ce3-a3fb-44ce-8a01-eb53d514f97f)

欢迎加入[脚本作者交流群](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=bONOrUWffNh7hIg42rIQLwSY-GGGj2l8&authKey=osgQDk41LUnOIFHPdIiDGMlIfaulXMz4QlssU4dZpIuY2jzsb5f%2FB8NAc0mzAP0m&noverify=0&group_code=764972801)

**Comment by huiyadanli** [comment]
@Yang-z @@Kupder 关于这个问题，我可以提供新的API直接读取几个配置目录的信息

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/dev/js/otherscript.html#runfilefromuser-string-path

![Image](https://github.com/user-attachments/assets/8ae191a6-9837-49e2-8797-da9453cd8520)
